---
title: "ds202_lab4"
author: "Anyesha Ray & McKenna Goffinet"
date: "March 22, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#packages
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
```


#read in data
```{r}
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2019.xlsx', sheet='Offensive')
bio <- read_excel('cyclonesFootball2019.xlsx', sheet='Biography')
str(defense)
str(offense)
str(bio)
```



#Clean Data  Part 1 Q1
```{r}
offense$Name = as.factor(offense$Name)
offense$Opponent_Opponent = as.factor(offense$Opponent_Opponent)
defense$Name = as.factor(defense$Name)
defense$Opponent_Opponent = as.factor(defense$Opponent_Opponent)
bio$Name = as.factor(bio$Name)
```



#Clean Data  Part 1 Q2
```{r}
defClean = defense %>% mutate_if(is.character, as.numeric)
offClean = offense %>% mutate_if(is.character, as.numeric)
bioClean = bio %>% mutate_at("Weight", as.numeric)

#check
#str(defClean)
#str(offClean)
#str(bioClean)
```


#Clean Data  Part 1 Q3
```{r}
bioClean = bioClean %>%
  separate('Height', c("Feet", "Inches"), 
           sep = "-(?=[^ ]+$)", remove = FALSE) %>%
  mutate_at("Feet", as.numeric) %>%
  mutate_at("Inches", as.numeric)
bioClean$Height = bioClean$Feet * 12 + bioClean$Inches
bioClean = bioClean %>% select(-Feet, -Inches)
         
```
#Clean data Part 2 Q1
```{r error=TRUE}
defCleanP2 = pivot_longer(defClean, cols = Tackles_Solo:Pass_PB, names_to = "Statistic", values_to = "Count", values_drop_na = TRUE)
head(defClean2,5)
```


#Clean data Part 2 Q2
```{r}
ggplot(data=defCleanP2, aes(defCleanP2$Count)) + geom_histogram(binwidth = 1, color="black", fill="lightblue") +
  facet_wrap(~ defCleanP2$Statistic) + labs(title=" Defense Skills Plots",y="Frequency", x="Number of Occurrences") 
```

Here the rare skills appear to be sacks, tackles assists and solo tackles because they have values that are not 0 but there are few values of the non zero kind. 


#Clean data Part 2 Q3
```{r}
defCleanP2Q3 = defCleanP2 %>%
  filter(Statistic == "Tackles_Solo", Opponent_Opponent %in% c("West Virginia","Kansas State")) %>% 
  select(-Statistic) %>%
  pivot_wider(names_from = Opponent_Opponent, values_from = Count)
ggplot(defCleanP2Q3, aes(x=defCleanP2Q3$`West Virginia`, y=defCleanP2Q3$`Kansas State`, color=green)) +
  geom_point(size=3, shape=20,fill="lightblue", color="black") + labs(title="Solo Tackles in WVU and KSU Games", x="West Virgina Solo Tackles", y="Kansas State Solo Tackles") 

```

Here it seems as though, Kansas State has a better defense. 










